name: AI Code Review with Deepseek

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ai_code_review:
    runs-on: ubuntu-latest

    permissions:  
        contents: read  
        pull-requests: write 

    steps:
      - name: AI 代码审查
        uses: eaglecloud-sec/ai-security-code@v1.0.1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            owner: ${{ github.repository_owner }}
            repo: ${{ github.event.repository.name }}
            pr_number: ${{ github.event.number }}
            
            ai_provider: 'deepseek'
            deepseek_api_key: ${{ secrets.DEEPSEEK_API_KEY }}
            deepseek_model: 'deepseek-chat'
            include_extensions: '.py,.go,'
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}